# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'RainyDayAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseDatabase', '10.29.0'
  pod 'FirebaseMessaging', '10.29.0'
  # Pods for RainyDayAPP
	

end
